version: '3.1'
services:

      nagios-server:
        image: nagios-server
        ports:
            - '80:80'
            - '22:22'
            - '5666'
        tty: true

      nagios-client:
        image: nagios-client-test
        ports: 
            - '80'
            - '22'
            - '5666:5666'
        tty: true
        privileged: true  
